version: "3"

services:
  app:
    build: .
    container_name: django-gunicorn
    restart: always
    env_file:
      - .env.prod
    ports:
      - "8000:8000"
    command:
      "gunicorn --workers=1 --bind=0.0.0.0:8000 postal_ranges.wsgi:application"
    volumes:
      - static_volume:/src/staticfiles

  nginx:
    image: nginx:1.17
    container_name: ngx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/src/staticfiles
    depends_on:
      - app

volumes:
   static_volume: