version: '3'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile

    volumes:
      - ./postal_ranges:/code
    env_file:
      - ./.env.dev
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    # command: ls -lrt